#!/usr/bin/env python3
"""Generate supabase/seed/elite_merchants_100.sql (100 elite merchants, 2 deals each)."""
from pathlib import Path

NAMES = [
    "Nairobi Fresh Market", "Globe Grill", "Elite Fashion Hub", "Westlands Coffee Co",
    "CBD Electronics Plus", "Karen Pharmacy", "Kilimani Bistro", "Eastleigh Spice House",
    "BBS Mall Gourmet", "Savanna Style", "Urban Threads", "Golden Plate Kitchen",
    "Metro Gadgets", "Bloom Beauty", "Harbor Café", "Prime Grocers",
    "Silk & Stitch", "Sunrise Bakery", "TechNest Mobile", "Wellness Corner",
    "Maasai Grill", "Palm Court Dining", "Velvet Boutique", "Green Basket",
    "Circuit City Hub", "Radiant Salon", "Mocha Lane", "Heritage Foods",
    "TrendSetters", "Cloud Nine Café", "SmartHome Store", "CarePlus Pharmacy",
    "Flame & Fork", "Organic Oasis", "Luxe Apparel", "Byte Bazaar",
    "Serene Spa", "Corner Deli", "Fashion Forward", "Power Tools Pro",
    "Sweet Crust", "Urban Pantry", "Designer Den", "Digital Depot",
    "FreshCuts Barbers", "Harvest Table", "Elite Sneakers", "Gadget Galaxy",
    "Tea & Tales", "Market Square Eats", "Chic Collective", "Home Essentials",
    "QuickFix Services", "Artisan Roast", "Style Studio", "Value Mart",
    "Phone Doctor", "Garden Plate", "Runway Retail", "Connect Hub",
    "Pastry Palace", "Neighborhood Nosh", "Tailor Made", "Screen Savers",
    "Juice Junction", "Mall Food Court Star", "Premium Fabrics", "Tech Traders",
    "Glow Beauty Bar", "Daily Bread Co", "Sport Elite", "Audio Avenue",
    "Noodle House", "Fresh Fare", "Urban Outfitters KE", "Repair Right",
    "Cocoa Corner", "Family Feast", "Denim District", "Camera Corner",
    "Smoothie Spot", "Grill Masters", "Boutique 254", "Laptop Lounge",
    "Spice Route", "Healthy Bites", "Formal Wear Co", "Gaming Gear",
    "Cupcake Cove", "Street Eats", "Shoe Sanctuary", "Watch World",
    "Ramen Republic", "Organic Select", "Kids Fashion Hub", "Printer Pro",
    "Bubble Tea Bar", "Steak Studio", "Accessories Avenue", "Drone Den",
    "Sushi Social", "Bulk Buy Mart", "Luxury Linens", "VR Ventures",
]

CATEGORIES = ["restaurant", "grocery", "fashion", "electronics", "café", "pharmacy", "services"]
IMAGE_BY_CAT = {
    "restaurant": "/deals/food-01.svg",
    "grocery": "/deals/grocery-01.svg",
    "fashion": "/deals/fashion-01.svg",
    "electronics": "/deals/services-01.svg",
    "café": "/deals/food-02.svg",
    "pharmacy": "/deals/grocery-02.svg",
    "services": "/deals/services-01.svg",
}
FLOORS = ["Ground Floor", "1st Floor", "2nd Floor", "Food Court"]
LOCATIONS = ["BBS Mall – Ground Floor", "BBS Mall – 1st Floor", "Westlands", "CBD", "Eastleigh"]

lines = [
    "-- AUTO-GENERATED by scripts/generate-elite-merchants-seed.py — do not edit by hand",
    "-- 100 elite merchants + 200 deals (1 flash + 1 standard per merchant)",
    "-- UUID namespace: b3/c3/d3 (no collision with rehearsal b0 or demo b1 seeds)",
    "BEGIN;",
    "",
    "INSERT INTO public.users (id, auth_uid, phone, email, full_name, role)",
    "SELECT",
    "  ('b3000000-0000-4000-a000-' || lpad(n::text, 12, '0'))::uuid,",
    "  NULL,",
    "  '+25470' || lpad((2000000 + n)::text, 7, '0'),",
    "  'elite.seed' || lpad(n::text, 3, '0') || '@maanta.app',",
    "  names[n],",
    "  'merchant_admin'",
    f"FROM generate_series(1, 100) AS n,",
    f"  (SELECT ARRAY{repr(NAMES)}::text[] AS names) AS t",
    "WHERE NOT EXISTS (",
    "  SELECT 1 FROM public.users u",
    "  WHERE u.id = ('b3000000-0000-4000-a000-' || lpad(n::text, 12, '0'))::uuid",
    ");",
    "",
]

# merchants insert via VALUES in chunks is easier in python
lines.append("INSERT INTO public.merchants (")
lines.append("  id, user_id, merchant_name, tier, status, elite_trial_active, trial_ends_at,")
lines.append("  node, what3words_address, mall_name, floor, unit_number, entrance_notes,")
lines.append("  phone, email, whatsapp, account_balance, outstanding_arrears,")
lines.append("  is_visible, is_shadow_banned, onboarded_at, trust_metric")
lines.append(")")
lines.append("SELECT * FROM (VALUES")

merchant_rows = []
for n in range(1, 101):
    name = NAMES[n - 1]
    cat = CATEGORIES[(n - 1) % len(CATEGORIES)]
    floor = FLOORS[(n - 1) % len(FLOORS)]
    loc = LOCATIONS[(n - 1) % len(LOCATIONS)]
    status = "pending" if n % 23 == 0 else "active"
    balance = 800 + (n % 17) * 100
    trust = round(0.72 + (n % 28) * 0.01, 2)
    merchant_rows.append(
        f"  (('c3000000-0000-4000-a000-' || lpad('{n}'::text, 12, '0'))::uuid, "
        f"('b3000000-0000-4000-a000-' || lpad('{n}'::text, 12, '0'))::uuid, "
        f"{name!r}, 'elite', {status!r}, true, NOW() + INTERVAL '30 days', "
        f"'BBS Mall', 'shops.lively.mall', 'BBS Mall', {floor!r}, "
        f"{chr(65 + (n - 1) % 26)!r} || '-' || lpad({((n - 1) % 40) + 1}::text, 2, '0'), "
        f"{cat + ' · ' + loc!r}, "
        f"'+25470' || lpad({2000000 + n}::text, 7, '0'), "
        f"'elite.seed' || lpad({n}::text, 3, '0') || '@maanta.app', "
        f"'+25470' || lpad({2000000 + n}::text, 7, '0'), "
        f"{balance}.00, 0, true, false, NOW() - ({n % 45} || ' days')::interval, {trust})"
    )

lines.append(",\n".join(merchant_rows))
lines.append(") AS v(id, user_id, merchant_name, tier, status, elite_trial_active, trial_ends_at,")
lines.append("  node, what3words_address, mall_name, floor, unit_number, entrance_notes,")
lines.append("  phone, email, whatsapp, account_balance, outstanding_arrears,")
lines.append("  is_visible, is_shadow_banned, onboarded_at, trust_metric)")
lines.append("WHERE NOT EXISTS (SELECT 1 FROM public.merchants m WHERE m.id = v.id);")
lines.append("")

# GPS update block
lines.extend([
    "DO $$",
    "BEGIN",
    "  IF EXISTS (",
    "    SELECT 1 FROM information_schema.columns",
    "    WHERE table_schema = 'public' AND table_name = 'merchants' AND column_name = 'lat'",
    "  ) THEN",
    "    UPDATE public.merchants m",
    "    SET lat = -1.2746 + ((n % 10) - 5) * 0.0002,",
    "        lng = 36.8501 + ((n % 7) - 3) * 0.00025,",
    "        updated_at = NOW()",
    "    FROM generate_series(1, 100) AS n",
    "    WHERE m.id = ('c3000000-0000-4000-a000-' || lpad(n::text, 12, '0'))::uuid;",
    "  END IF;",
    "END $$;",
    "",
])

# Deals - flash and standard per merchant
lines.append("INSERT INTO public.deals (")
lines.append("  id, merchant_id, node, title, description, image_url,")
lines.append("  discount_type, discount_value, deal_type, flash_duration_hours,")
lines.append("  is_active, boost_active, max_claims, claims_count, starts_at,")
lines.append("  price_kes, compare_at_kes, charges, expires_at")
lines.append(")")
lines.append("SELECT")
lines.append("  ('d3000000-0000-4000-a000-' || lpad(deal_n::text, 12, '0'))::uuid,")
lines.append("  ('c3000000-0000-4000-a000-' || lpad(n::text, 12, '0'))::uuid,")
lines.append("  'BBS Mall',")
lines.append("  CASE WHEN deal_n % 2 = 1 THEN 'FLASH: ' || names[n] || ' today special'")
lines.append("       ELSE names[n] || ' — member offer' END,")
lines.append("  'Synthetic elite deal for rehearsal — show your Maanta code at the counter.',")
lines.append("  images[1 + ((n - 1) % array_length(images, 1))],")
lines.append("  'fixed', 200, CASE WHEN deal_n % 2 = 1 THEN 'flash' ELSE 'standard' END,")
lines.append("  6, true, false, CASE WHEN deal_n % 2 = 1 THEN 15 ELSE 30 END, 0,")
lines.append("  NOW() - INTERVAL '2 hours',")
lines.append("  (400 + (n % 20) * 50)::numeric,")
lines.append("  (800 + (n % 20) * 80)::numeric,")
lines.append("  '[]'::jsonb,")
lines.append("  CASE WHEN deal_n % 2 = 1 THEN NOW() + INTERVAL '6 hours'")
lines.append("       ELSE NOW() + INTERVAL '14 days' END")
lines.append("FROM generate_series(1, 100) AS n,")
lines.append("     generate_series(n * 2 - 1, n * 2) AS deal_n,")
lines.append(f"     (SELECT ARRAY{repr(NAMES)}::text[] AS names) AS t,")
lines.append(f"     (SELECT ARRAY{list(IMAGE_BY_CAT.values())!r}::text[] AS images) AS img")
lines.append("WHERE NOT EXISTS (")
lines.append("  SELECT 1 FROM public.deals d")
lines.append("  WHERE d.id = ('d3000000-0000-4000-a000-' || lpad(deal_n::text, 12, '0'))::uuid")
lines.append(");")
lines.append("")
lines.append("COMMIT;")
lines.append("")
lines.append("SELECT count(*) AS elite_merchants FROM merchants WHERE id::text LIKE 'c3000000-%';")
lines.append("SELECT count(*) AS elite_deals FROM deals WHERE id::text LIKE 'd3000000-%';")

out = Path(__file__).resolve().parents[1] / "supabase/seed/elite_merchants_100.sql"
out.write_text("\n".join(lines) + "\n")
print(f"Wrote {out}")
